# Generated by Django 5.2.17 on 2026-09-23 22:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_fuentes_sin_directorios'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='puesto')),
                ('company_name', models.CharField(max_length=200, verbose_name='empresa (según el portal)')),
                ('portal', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(max_length=600, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='ubicación')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='puntuación')),
                ('match', models.CharField(blank=True, choices=[('domain', 'Dominio'), ('name', 'Nombre'), ('fuzzy', 'Nombre parecido'), ('', 'Sin empresa')], max_length=8, verbose_name='cruce')),
                ('source', models.CharField(default='career-ops', max_length=40, verbose_name='origen')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='fila original')),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='companies.company')),
            ],
            options={
                'verbose_name': 'oferta',
                'verbose_name_plural': 'ofertas',
                'ordering': ['-published_on', '-id'],
            },
        ),
    ]
