# Generated by Django 5.2.17 on 2026-09-17 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120, verbose_name='nombre completo')),
                ('headline', models.CharField(blank=True, max_length=120, verbose_name='titular')),
                ('summary', models.TextField(blank=True, verbose_name='resumen')),
                ('education', models.JSONField(blank=True, default=list, verbose_name='formación')),
                ('experience', models.JSONField(blank=True, default=list, verbose_name='experiencia')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='habilidades')),
                ('languages', models.JSONField(blank=True, default=list, verbose_name='idiomas')),
                ('company_sizes', models.JSONField(blank=True, default=list, verbose_name='tamaño de empresa')),
                ('work_languages', models.JSONField(blank=True, default=list, verbose_name='idiomas de trabajo')),
                ('interests', models.TextField(blank=True, verbose_name='intereses')),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('parsed_model', models.CharField(blank=True, max_length=64)),
                ('parsed_prompt_version', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='catalog.category', verbose_name='categorías')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('zones', models.ManyToManyField(blank=True, to='catalog.zone', verbose_name='zonas')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='CVDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='nombre de archivo')),
                ('size', models.PositiveIntegerField(verbose_name='tamaño (bytes)')),
                ('sha256', models.CharField(max_length=64)),
                ('data', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
            },
        ),
    ]
