# Generated by Django 5.2.17 on 2026-09-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discovered_sectors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
