# Generated by Django 5.2.17 on 2026-09-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_discovered_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parses_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='parses_today',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
