# Generated by Django 5.2.17 on 2026-09-23 21:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_fuentes_sin_directorios'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('kind', models.CharField(choices=[('home', 'Inicio'), ('about', 'Sobre nosotros'), ('team', 'Equipo'), ('jobs', 'Empleo'), ('contact', 'Contacto')], max_length=16, verbose_name='tipo')),
                ('status_code', models.PositiveSmallIntegerField()),
                ('lang', models.CharField(blank=True, max_length=12, verbose_name='idioma declarado')),
                ('text', models.TextField(verbose_name='texto visible')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='companies.company')),
            ],
            options={
                'verbose_name': 'página',
                'verbose_name_plural': 'páginas',
                'constraints': [models.UniqueConstraint(fields=('company', 'url'), name='unique_company_page')],
            },
        ),
        migrations.CreateModel(
            name='Enrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_status', models.CharField(choices=[('pending', 'Pendiente'), ('ok', 'Rastreada'), ('no_website', 'Sin web'), ('not_a_site', 'Solo redes sociales'), ('robots', 'robots.txt no lo permite'), ('unreachable', 'Web caída o inaccesible'), ('not_html', 'La web no es HTML')], default='pending', max_length=16, verbose_name='estado del rastreo')),
                ('crawl_error', models.CharField(blank=True, max_length=300)),
                ('crawled_at', models.DateTimeField(blank=True, null=True)),
                ('pages_hash', models.CharField(blank=True, max_length=64)),
                ('emails', models.JSONField(blank=True, default=list)),
                ('socials', models.JSONField(blank=True, default=dict, verbose_name='redes sociales')),
                ('is_company_site', models.BooleanField(null=True, verbose_name='la web es de la empresa')),
                ('summary', models.TextField(blank=True, verbose_name='resumen')),
                ('services', models.JSONField(blank=True, default=list, verbose_name='servicios')),
                ('clients', models.JSONField(blank=True, default=list, verbose_name='clientes y proyectos')),
                ('size_estimate', models.CharField(choices=[('micro', 'Micro (1-9)'), ('pequena', 'Pequeña (10-49)'), ('mediana', 'Mediana (50-249)'), ('grande', 'Grande (250+)'), ('desconocido', 'Desconocido')], default='desconocido', max_length=16, verbose_name='tamaño estimado')),
                ('requires_catalan', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('desconocido', 'Desconocido')], default='desconocido', max_length=16, verbose_name='¿requiere catalán?')),
                ('site_languages', models.JSONField(blank=True, default=list, verbose_name='idiomas de la web')),
                ('jobs_url', models.URLField(blank=True, max_length=500, verbose_name='página de empleo')),
                ('hiring_note', models.CharField(blank=True, max_length=300, verbose_name='señales de contratación')),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_pages_hash', models.CharField(blank=True, max_length=64)),
                ('extraction_model', models.CharField(blank=True, max_length=64)),
                ('extraction_prompt_version', models.CharField(blank=True, max_length=64)),
                ('fit_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='encaje (0-100)')),
                ('fit_reason', models.TextField(blank=True, verbose_name='justificación')),
                ('hook', models.TextField(blank=True, verbose_name='gancho para presentarse')),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('profile_hash', models.CharField(blank=True, max_length=64)),
                ('scoring_model', models.CharField(blank=True, max_length=64)),
                ('scoring_prompt_version', models.CharField(blank=True, max_length=64)),
                ('error', models.CharField(blank=True, max_length=300, verbose_name='último error de IA')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment', to='companies.company')),
            ],
            options={
                'verbose_name': 'enriquecimiento',
                'verbose_name_plural': 'enriquecimientos',
                'indexes': [models.Index(fields=['-fit_score'], name='enrichment__fit_sco_804875_idx')],
            },
        ),
    ]
