# Generated by Django 5.2.17 on 2026-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrichment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrichment",
            name="extraction_attempts",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="extracciones fallidas seguidas"
            ),
        ),
    ]
