# Generated by Django 5.2.17 on 2026-09-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0002_extraction_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichment',
            name='fit_breakdown',
            field=models.JSONField(blank=True, default=dict, verbose_name='encaje por criterios'),
        ),
    ]
