# Generated by Django 5.2.17 on 2026-09-18 13:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('url', models.CharField(max_length=500)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('body', models.TextField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'respuesta cacheada',
                'verbose_name_plural': 'respuestas cacheadas',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name='código postal')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='ciudad')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=300, verbose_name='web')),
                ('domain', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='dominio')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.CharField(blank=True, max_length=255, verbose_name='horario (OSM opening_hours)')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_count', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0, verbose_name='confianza')),
                ('field_sources', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='categoría')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.zone', verbose_name='zona')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['-confidence_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('osm', 'OpenStreetMap'), ('foursquare', 'Foursquare OS Places'), ('sortlist', 'Sortlist'), ('clutch', 'Clutch'), ('paginas_amarillas', 'Páginas Amarillas'), ('association', 'Asociación sectorial'), ('manual', 'Manual')], max_length=32, verbose_name='fuente')),
                ('external_id', models.CharField(max_length=120, verbose_name='id externo')),
                ('name', models.CharField(max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='datos crudos')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='companies.company')),
            ],
            options={
                'verbose_name': 'registro de fuente',
                'verbose_name_plural': 'registros de fuente',
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['lat', 'lng'], name='companies_c_lat_ed47a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcerecord',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_source_record'),
        ),
    ]
