# Generated by Django 5.2.17 on 2026-09-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcerecord',
            name='source',
            field=models.CharField(choices=[('osm', 'OpenStreetMap'), ('foursquare', 'Foursquare OS Places'), ('opendata_bcn', 'Cens de locals (Ajuntament de Barcelona)'), ('manual', 'Manual')], max_length=32, verbose_name='fuente'),
        ),
    ]
