# Generated by Django 5.2.17 on 2026-09-18 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('discover', 'Descubrimiento'), ('enrich', 'Enriquecimiento')], max_length=16, verbose_name='tipo')),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('running', 'En marcha'), ('success', 'Terminado'), ('failed', 'Fallido')], default='queued', max_length=16, verbose_name='estado')),
                ('trigger', models.CharField(choices=[('schedule', 'Programado'), ('manual', 'Manual (línea de comandos)'), ('app', 'Desde la app')], default='manual', max_length=16, verbose_name='origen')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='métricas')),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='coste estimado (USD)')),
                ('summary', models.TextField(blank=True, verbose_name='resumen')),
                ('error', models.TextField(blank=True)),
                ('github_run_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('github_run_url', models.URLField(blank=True, max_length=300)),
                ('github_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ejecución',
                'verbose_name_plural': 'ejecuciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
