# Generated by Django 5.2.17 on 2026-09-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrun',
            name='kind',
            field=models.CharField(choices=[('discover', 'Descubrimiento'), ('enrich', 'Enriquecimiento'), ('personalize', 'Búsqueda personalizada')], max_length=16, verbose_name='tipo'),
        ),
    ]
