# Generated by Django 5.2.17 on 2026-09-23 22:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_seed'),
        ('companies', '0002_fuentes_sin_directorios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='día')),
                ('slot', models.CharField(choices=[('manana', 'Mañana (9:30-14:00)'), ('tarde', 'Tarde (15:30-19:00)'), ('dia', 'Todo el día (9:30-19:00)')], default='manana', max_length=8, verbose_name='franja')),
                ('start_lat', models.FloatField(blank=True, null=True)),
                ('start_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.zone', verbose_name='zona')),
            ],
            options={
                'verbose_name': 'ruta',
                'verbose_name_plural': 'rutas',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='orden')),
                ('state', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'CV entregado'), ('visitada', 'Visitada'), ('cerrada', 'Cerrada'), ('saltada', 'Saltada')], default='pendiente', max_length=12, verbose_name='estado')),
                ('distance_m', models.PositiveIntegerField(default=0, verbose_name='distancia desde la parada anterior (m)')),
                ('previous_status', models.CharField(blank=True, max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='companies.company')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route')),
            ],
            options={
                'verbose_name': 'parada',
                'verbose_name_plural': 'paradas',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('route', 'company'), name='unique_route_company')],
            },
        ),
    ]
