# Generated by Django 5.2.17 on 2026-09-24 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='closed_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracking.note'),
        ),
    ]
