# Generated by Django 5.2.17 on 2026-09-23 22:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_fuentes_sin_directorios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=8, verbose_name='prioridad')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('note', models.CharField(blank=True, max_length=280, verbose_name='nota')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='companies.company')),
            ],
            options={
                'verbose_name': 'favorita',
                'verbose_name_plural': 'favoritas',
                'ordering': ['position', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='nota')),
                ('is_status_change', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='companies.company')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('planificado', 'Planificado'), ('visitado', 'Visitado'), ('cv_entregado', 'CV entregado'), ('volver', 'Volver'), ('descartado', 'Descartado')], db_index=True, default='pendiente', max_length=16, verbose_name='estado')),
                ('visited_on', models.DateField(blank=True, null=True, verbose_name='fecha de la visita')),
                ('contact', models.CharField(blank=True, max_length=120, verbose_name='persona de contacto')),
                ('next_action', models.CharField(blank=True, max_length=200, verbose_name='próxima acción')),
                ('next_action_on', models.DateField(blank=True, null=True, verbose_name='fecha de la próxima acción')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='companies.company')),
            ],
            options={
                'verbose_name': 'visita',
                'verbose_name_plural': 'visitas',
            },
        ),
    ]
