# Generated by Django 5.2.17 on 2026-09-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('cv_parse', 'Parseo de CV'), ('enrichment', 'Enriquecimiento de empresa'), ('scoring', 'Scoring de encaje')], max_length=32, verbose_name='propósito')),
                ('model', models.CharField(max_length=64, verbose_name='modelo')),
                ('prompt_version', models.CharField(max_length=64, verbose_name='versión del prompt')),
                ('input_hash', models.CharField(max_length=64, unique=True, verbose_name='hash de entrada')),
                ('response', models.JSONField(verbose_name='respuesta validada')),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='coste (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'llamada LLM',
                'verbose_name_plural': 'llamadas LLM',
                'ordering': ['-created_at'],
            },
        ),
    ]
